name: "Actions Status Space Channel"
description: "Post Github Actions CI status to Space Channel"
author: "imamhadid"

inputs:
  webhook:
    description: "Space webhook endpoint. If not set, env.SPACE_WEBHOOK will be used."
    required: false
  token:
    description: "Space webhook token."
    required: false
  status:
    description: "Job status. Should be bound to job.status. Default to success."
    required: false
    default: ${{ job.status }}
  job:
    description: "Deprecated. Job name included in message title. Same as title input."
    required: false
  content:
    description: "Content. Shown as an message outside of the embed. See [Mention to user/role](#mention-to-user-role)"
    required: false
  title:
    description: "String included in embed title. Overrides job input."
    required: false
    default: ${{ github.workflow }}
  description:
    description: "Description included in message"
    required: false
  image:
    description: "Image attached to the message"
    required: false
  color:
    description: "Overrides Space embed color"
    required: false
  url:
    description: "URL to jump when the title is clicked"
    required: false
  username:
    description: "Overrides Space webhook username"
    required: false
  avatar_url:
    description: "Overrides Space webhook avatar url"
    required: false
  nofail:
    description: "This action won't make workflow failed by default."
    required: false
    default: "true"
  nocontext:
    description: "Suppress GitHub context fields"
    required: false
    default: "false"
  noprefix:
    description: "Avoid appending job status to title"
    required: false
    default: "false"
  nodetail:
    description: "Suppress detailed embed fields"
    required: false
    default: "false"
  notimestamp:
    description: "Avoid appending timestamp"
    required: false
    default: "false"

runs:
  using: "node20"
  main: "src/main.ts"

branding:
  color: "blue"
  icon: "send"