"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MAX_WEBHOOK_CONTENT_LENGTH = exports.MAX_EMBED_FIELD_VALUE_LENGTH = exports.MAX_EMBED_FIELD_NAME_LENGTH = exports.MAX_EMBED_DESCRIPTION_LENGTH = exports.MAX_EMBED_TITLE_LENGTH = void 0;
exports.MAX_EMBED_TITLE_LENGTH = 256;
exports.MAX_EMBED_DESCRIPTION_LENGTH = 4096;
exports.MAX_EMBED_FIELD_NAME_LENGTH = 256;
exports.MAX_EMBED_FIELD_VALUE_LENGTH = 1024;
exports.MAX_WEBHOOK_CONTENT_LENGTH = 2000;
